[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Max Davidson <davidsonmax@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
num = "0.2.0"
regex = "1.1.0"
itertools = "0.7.11"
chrono = "0.4.6"
