name: Rust

on: [push]

jobs:
  test:
    name: "Run tests on ${{ matrix.rust-channel }} channel"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-channel: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test --verbose
      env:
        RUSTUP_TOOLCHAIN: ${{ matrix.rust-channel }}
